p_opt: 0.0
sizes: [20, 80]
count: sdbl
grow:
  name_prefix: ПерфЭлемент
  catalog: { name: Номенклатура }
  accumulation: { register: ДвиженияТоваров, registrar: ВводТоваров, record: { Склад: Основной, Номенклатура: "$unit", Количество: 10 } }
call: 'КодКандидата.{{ENTRY}}(Дата(2026,1,1), КонецДня(Дата(2026,12,31)), Спр("Склады", "Основной склад"))'
